version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: "./docker/python/Dockerfile"
    working_dir: /var/www/app
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./src:/var/www/app/src
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TX: 'Azia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data: